version: '3'
services:
  # Espacio para tu apigateway
  nginx:
    image: nginx:latest
    ports:
      - 5000:8080
    volumes:
        - ./api-gateway/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - monitor
        - registro_usuario
        - consulta_usuario
    networks:
      network:

  # Servidor principal con codigo de servicio de registro de usuarios
  registro_usuario:
    build:
      context: ./registro_usuario
    networks:
      network:

  registro_usuario_fall_back:
    build:
      context: ./registro_usuario
    networks:
      network:

  consulta_usuario:
    build:
      context: ./consulta_usuario
    networks:
      network:
    ports:
      - 5001:5001

  db_usuario:
    build:
      context: ./db_usuario
    networks:
      network:
    ports:
      - 5002:5002

  monitor:
    build:
      context: ./monitor
    environment:
      - SERVER_X_NAME=experimento-1-registro_usuario-1
      - SERVER_Y_NAME=experimento-1-registro_usuario_fall_back-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      network:

networks:
  network:
